#%RAML 0.8
title: SFDC HC System API
version: v1
baseUri: http://healthcare-fhir2sfdchealth-ehr-system-api.cloudhub.io/api

/patients/{patientIDType}/{patientID}:
  displayName: patient
  uriParameters:
    patientID:
      type: string
      description: Patient ID
    patientIDType:
      type: string
      description: ID Type like MRN
  put:
    description: "Update Patient in the SFDC instance"
    body:
      application/json:
        example: !include ../patient/patient-fhir-request.json
    responses:
      200:
        body:
          application/json:   
  /observations:
    post:  
      description: "Create new Observation in the SFDC instance"
      body:
        application/json:
          example: !include ../observation/observation-fhir-request.json
      responses:
        200:
          body:
            application/json:            
  /conditions:
    post:  
      description: "Create new Condition in the SFDC instance"
      body:
        application/json:
          example: !include ../condition/condition-fhir-request.json
      responses:
        200:
          body:
            application/json:                
    put:  
      description: "Upsert Condition in the SFDC instance"
      body:
        application/json:
          example: !include ../condition/condition-fhir-request.json
      responses:
        200:
          body:
            application/json:              
  /medications:
    post:  
      description: "Create new Medication in the SFDC instance"
      body:
        application/json:
          example: !include ../medication/medicationorder-fhir-request.json
      responses:
        200:
          body:
            application/json:               
  /allergies:
    post:  
      description: "Create new Allergy in the SFDC instance"
      body:
        application/json:
          example: !include ../allergyIntolerance/allergyIntolerance-fhir-request.json
      responses:
        200:
          body:
            application/json:               
    put:  
      description: "Upsert Allergy in the SFDC instance"
      body:
        application/json:
          example: !include ../allergyIntolerance/allergyIntolerance-fhir-request.json
      responses:
        200:
          body:
            application/json:        
  /devices:             
    put:  
      description: "Upsert Devices in the SFDC instance"
      body:
        application/json:
          example: !include devices-fhir-request.json
      responses:
        200:
          body:
            application/json:
  /scheduling:
    post:  
      description: "Create new Scheduling in the SFDC instance"
      responses:
        200:
          body:
            application/json:              
  /encounters:
    put:  
      description: "Create new Encounter and respective Encounter Practitioner in the SFDC instance"
      body:
        application/json:
          example: !include ../appointment/appointment-fhir-request.json
      responses:
        200:
          body:
            application/json:
/practitioners:
  displayName: Practitioners
  /{practitionerID}:
    uriParameters:
      practitionerID:
        type: string
        description: Practitioner ID
    post:  
      description: "Create new Practitioner in the SFDC instance"
      body:
        application/json:
          example: !include ../practitioner/practitioner-fhir-request.json
      responses:
        200:
          body:
            application/json:
  put:
    description: "Upsert Practitioners in the SFDC instance"
    body:
      application/json:
        example: !include ../practitioner/practitioners-fhir-request.json
    responses:
      200:
        body:
          application/json: